/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MercadosRouteImport } from './routes/mercados'
import { Route as EstrategiasRouteImport } from './routes/estrategias'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const MercadosRoute = MercadosRouteImport.update({
  id: '/mercados',
  path: '/mercados',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiasRoute = EstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estrategias': typeof EstrategiasRoute
  '/mercados': typeof MercadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estrategias': typeof EstrategiasRoute
  '/mercados': typeof MercadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estrategias': typeof EstrategiasRoute
  '/mercados': typeof MercadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/estrategias' | '/mercados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/estrategias' | '/mercados'
  id: '__root__' | '/' | '/contacto' | '/estrategias' | '/mercados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EstrategiasRoute: typeof EstrategiasRoute
  MercadosRoute: typeof MercadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mercados': {
      id: '/mercados'
      path: '/mercados'
      fullPath: '/mercados'
      preLoaderRoute: typeof MercadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategias': {
      id: '/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof EstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EstrategiasRoute: EstrategiasRoute,
  MercadosRoute: MercadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
